version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: vijayasarathism
      POSTGRES_PASSWORD: password123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    restart: unless-stopped

volumes:
  db:
